// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJljlMrksMACrxU-NYP6HU8gz8lkicDqU',
    appId: '1:728398470828:web:1bc704dbff08757aa04909',
    messagingSenderId: '728398470828',
    projectId: 'ecoflux-8cf4e',
    authDomain: 'ecoflux-8cf4e.firebaseapp.com',
    databaseURL: 'https://ecoflux-8cf4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoflux-8cf4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzTBc9Vtq4NS3TRLC2IqFiv2w6kY8vFgo',
    appId: '1:728398470828:android:c1a65da766a39741a04909',
    messagingSenderId: '728398470828',
    projectId: 'ecoflux-8cf4e',
    databaseURL: 'https://ecoflux-8cf4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoflux-8cf4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWISFNwgg-g8MZpq0_T5wdBiMw5xn0hww',
    appId: '1:728398470828:ios:cb60f58badf83204a04909',
    messagingSenderId: '728398470828',
    projectId: 'ecoflux-8cf4e',
    databaseURL: 'https://ecoflux-8cf4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoflux-8cf4e.firebasestorage.app',
    iosBundleId: 'com.example.ecoflux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWISFNwgg-g8MZpq0_T5wdBiMw5xn0hww',
    appId: '1:728398470828:ios:cb60f58badf83204a04909',
    messagingSenderId: '728398470828',
    projectId: 'ecoflux-8cf4e',
    databaseURL: 'https://ecoflux-8cf4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoflux-8cf4e.firebasestorage.app',
    iosBundleId: 'com.example.ecoflux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJljlMrksMACrxU-NYP6HU8gz8lkicDqU',
    appId: '1:728398470828:web:f4ad64a64168cd04a04909',
    messagingSenderId: '728398470828',
    projectId: 'ecoflux-8cf4e',
    authDomain: 'ecoflux-8cf4e.firebaseapp.com',
    databaseURL: 'https://ecoflux-8cf4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoflux-8cf4e.firebasestorage.app',
  );
}
